version: '3'

services:
  app:
    build: .
    environment:
      - PORT=8000
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: streamlit run app.py --browser.serverAddress 0.0.0.0 --server.runOnSave true --server.port 8000
